### ISSUE TITLE
Try to make it work with angular5

### ISSUE THREAD

**Issue by icarus31** [siteslave/clarity-angular4-electron#1]
Hi,

This is not really an issue, but wanted to know if you tried branch with Angular 5 and if so, did you find any issue?

From my side, I have:
$ ng serve
Cannot find module '../../plugins/insert-concat-assets-webpack-plugin'
Error: Cannot find module '../../plugins/insert-concat-assets-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\myproject\node_modules\@angular\cli\models\webpack-configs\common.js:7:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\myproject\node_modules\@angular\cli\models\webpack-configs\index.js:7:10)-configs\index.js:7:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

Regards

**Comment by icarus31** [comment]
Uninstalled and reinstalled angular-cli and it worked with angular 5. Sorry about that
